import { notFound } from "next/navigation";
import { createClient as createServiceClient } from "@supabase/supabase-js";
import { DyagnoLogo } from "@/components/brand";

export const dynamic = "force-dynamic";

function serviceClient() {
  return createServiceClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}

export default async function SharePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const supabase = serviceClient();

  const { data: convo } = await supabase
    .from("conversations")
    .select("id, title, appliance_type, created_at, share_token")
    .eq("share_token", token)
    .single();

  // Revoked or invalid token → 404
  if (!convo || !convo.share_token) notFound();

  const { data: messages } = await supabase
    .from("messages")
    .select("id, role, content, created_at")
    .eq("conversation_id", convo.id)
    .order("created_at", { ascending: true });

  const { data: partRows } = await supabase
    .from("part_mentions")
    .select("part_name, part_number")
    .eq("session_id", convo.id);

  // Dedupe parts
  const partMap = new Map<string, string | null>();
  for (const p of partRows ?? []) {
    const key = (p.part_name ?? "").trim().toLowerCase();
    if (key && !partMap.has(key)) partMap.set(key, p.part_number ?? null);
  }
  const parts = [...partMap.entries()].map(([name, number]) => ({ name, number }));

  // Extract safety warnings from assistant messages
  const warnings: string[] = [];
  for (const m of messages ?? []) {
    if (m.role !== "assistant") continue;
    for (const line of (m.content ?? "").split("\n")) {
      if (/^(WARNING|CAUTION|DANGER)/i.test(line.trim())) warnings.push(line.trim());
    }
  }

  return (
    <div className="min-h-screen bg-dark-chrome">
      <header className="border-b border-steel-border bg-dark-carbon">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <DyagnoLogo size={28} variant="dark" showWordmark />
          <span className="text-xs text-warm-gold/40">Shared diagnosis</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8 space-y-8">
        <div>
          <h1 className="text-2xl font-bold text-warm-gold" style={{ fontFamily: "var(--font-space-grotesk)" }}>
            {convo.title ?? "Appliance diagnosis"}
          </h1>
          <div className="flex items-center gap-2 mt-2">
            {convo.appliance_type && (
              <span className="text-xs text-warm-gold/50 bg-dark-carbon border border-steel-border rounded-full px-3 py-1">{convo.appliance_type}</span>
            )}
            <span className="text-xs text-warm-gold/30">{new Date(convo.created_at).toLocaleDateString()}</span>
          </div>
        </div>

        {warnings.length > 0 && (
          <div className="space-y-2">
            <p className="text-xs uppercase tracking-wider text-amber-400/70 font-semibold">Safety warnings</p>
            {warnings.map((w, i) => (
              <div key={i} className="flex gap-2 bg-amber-900/20 border border-amber-700/30 rounded-lg px-3 py-2">
                <span className="shrink-0">&#9888;</span>
                <span className="text-amber-300 text-xs leading-relaxed">{w}</span>
              </div>
            ))}
          </div>
        )}

        {parts.length > 0 && (
          <div className="space-y-2">
            <p className="text-xs uppercase tracking-wider text-warm-gold/40 font-semibold">Parts mentioned</p>
            <div className="flex flex-wrap gap-2">
              {parts.map((p, i) => (
                <span key={i} className="text-xs bg-dark-carbon border border-forge-amber/20 text-forge-amber rounded-md px-2.5 py-1">
                  {p.name}{p.number && p.number !== p.name ? ` (${p.number})` : ""}
                </span>
              ))}
            </div>
          </div>
        )}

        <div className="space-y-4">
          <p className="text-xs uppercase tracking-wider text-warm-gold/40 font-semibold">Conversation</p>
          {(messages ?? []).map((m) => (
            <div key={m.id} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}>
              <div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-relaxed whitespace-pre-wrap ${
                m.role === "user"
                  ? "bg-forge-amber text-ink font-medium rounded-br-sm"
                  : "bg-dark-carbon border border-steel-border text-warm-gold rounded-bl-sm"
              }`}>
                {m.content}
              </div>
            </div>
          ))}
        </div>

        <div className="text-center pt-6 border-t border-steel-border">
          <p className="text-xs text-warm-gold/30">Generated by Dyagno &mdash; AI Appliance Repair Intelligence</p>
        </div>
      </main>
    </div>
  );
}
